version: '3.2'

volumes:
  postgres_data_dev: {}

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    image: starter-graphene-nginx
    container_name: starter-graphene-nginx
    depends_on:
      - api
    env_file:
     - ./.env
    ports:
      - 80:80

  db:
    restart: always
    image: postgres:9.6.5-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - 5432:5432
    command: -c fsync=off -c synchronous_commit=off -c full_page_writes=off

  redis:
    container_name: starter_graphene_redis
    image: redis:latest
    restart: always

  api:
    build: .
    image: starter-graphene-api
    container_name: starter-graphene-api
    volumes:
      - type: bind
        source: .
        target: /starter-graphene-api
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - IN_DOCKER=1
    env_file:
     - ./.env
    ports:
      - 8000:8000
